### PR TITLE
Adding constant CMD_NEIGHBORING_VEHICLES

### PR DESCRIPTION
**Pull request by Tambup**
We added this new constant to be able to do a more safe lane change of platoons in [plexe PR#24](https://github.com/michele-segata/plexe/pull/24).

It's a very small PR, but that's what we needed.

Best.

### CODE REVIEW

**Comment by sommer** [comment]
Shouldn't this be the ID of a variable, rather than that of a command? Checking the SUMO constants at https://github.com/eclipse/sumo/blob/v1_10_0/src/libsumo/TraCIConstants.h#L1031, it seems that the SUMO developers would agree.

**Comment by Tambup** [comment]
Yes, you're right, my mistake. I rename the variable as they made, "VAR_NEIGHBORS".

**Comment by Tambup** [comment]
Now it's as it should.

**Comment by sommer** [comment]
Added, now ready for https://github.com/michele-segata/plexe/pull/24

**Pull request merged**
