### PR TITLE
Update VeinsInetMobility to be compatible with latest INET IMobility

### PR DESCRIPTION
**Pull request by chaotictoejam**
Jun 8th commit for INET made veins_inet to not be compatible with the latest INET IMobility. Commit found here: 
https://github.com/inet-framework/inet/commit/6f75037035effacee211cfbf42e1fb5fdabe340e

This PR updates VeinsInetMobility to match IMobility's contract.

### CODE REVIEW

**Comment by sommer** [comment]
Would this PR allow whitelisting additional INET versions? How does this impact the compatibility with older INET versions?

**Comment by chaotictoejam** [comment]
@sommer I added a version check for INET 4.2 so if it is not >=4.2 it does the previous method signatures, and tested its compatibility with INETs 4.1.x branch

**Comment by sommer** [comment]
Super, thanks! Seems like we'll have to hold off on merging until INET releases a new version, though. The last release, INET 4.2.0, still uses the "old" return types so we cannot yet determine when to use the new ones.

**Comment by chaotictoejam** [comment]
Fair enough, for now, this is a solution for those using the INET master branch version. I'll keep an eye on out for when INET releases their new version.

**Comment by sommer** [comment]
with INET 4.3.0 released, we now have a target release to check for

**Comment by sommer** [comment]
merged (with adapted checks). Much appreciated! Seems like Veins is now ready for INET 4.3.0.

**Pull request closed without merging**
