### PR TITLE
Additional TraCI commands

### PR DESCRIPTION
**Pull request by abdelaha**
I have added two more TraCI commands which are important for many scenarios.  The first command (getRoadMapPos) converts the Cartesian coordination of a node to its road map position. This is very important to retrieve the vehicle map information from its beacon message without accessing the vehicle object. The second command is getSumoCurrentTime() which is useful to synchronize my applications self messages with SUMO.

### CODE REVIEW

**Comment by sommer** [comment]
Many thanks for proposing an improvement to Veins! I like the idea of having a command to get the current SUMO edge name, offset, and lane number from OMNeT++ coordinates.

I don't quite get the necessity of the other command (for getting the current SUMO time step), though. Shouldn't the OMNeT++ and the SUMO time be in sync always?

Also, your pull request proposes to remove lots of config files that the OMNeT++ IDE needs to recognize the project as an Eclipse CDT project.

Lastly, if you want to make your code easier to integrate with the current Veins code, it'd be nice if it followed the code style of existing code. Veins now includes a config file for clang-format (`.clang-format`) and uncrustify (`.uncrustify.cfg`) to make this almost automatic.

**Comment by abdelaha** [comment]
Thank you for your response! 

Regarding the second command (get SUMO time), typically, sumo and omnet++ have the same time but they are not always synchronized. I was trying to create an event (self msg in traffic light object) at each time the traffic light should change its state. Hence, I used the command `getAssumedNextSwitchTime()` to determine the event time. But, It did not always work as expected since 'getAssumedNextSwitchTime()' may return an event time in the past which happend when Omnet++ time is ahead SUMO. I think the main reson for this is that omnet++ has a finer time granularity than SUMO. For instance, the following code 'std::cout<< "@(simtTime = " << simTime() << "), SUMO Time (getSumoCurrentTime()): " << traci->getSumoCurrentTime() << endl;' results in: 

```
@(simtTime = 65.0001), SUMO Time (getSumoCurrentTime()): 65000
@(simtTime = 68.518615026546), SUMO Time (getSumoCurrentTime()): 68500
@(simtTime = 68.532713858871), SUMO Time (getSumoCurrentTime()): 68500
@(simtTime = 68.975366647292), SUMO Time (getSumoCurrentTime()): 68500
@(simtTime = 68.981585120545), SUMO Time (getSumoCurrentTime()): 68500
@(simtTime = 69.01340570836), SUMO Time (getSumoCurrentTime()): 69000
@(simtTime = 69.019341955072), SUMO Time (getSumoCurrentTime()): 69000
@(simtTime = 69.077300762463), SUMO Time (getSumoCurrentTime()): 69000
@(simtTime = 69.080820043043), SUMO Time (getSumoCurrentTime()): 69000
@(simtTime = 69.442610049149), SUMO Time (getSumoCurrentTime()): 69000
@(simtTime = 69.484608621972), SUMO Time (getSumoCurrentTime()): 69000
@(simtTime = 69.499433378044), SUMO Time (getSumoCurrentTime()): 69000
@(simtTime = 69.544602199105), SUMO Time (getSumoCurrentTime()): 69500
@(simtTime = 69.547124896718), SUMO Time (getSumoCurrentTime()): 69500
@(simtTime = 69.550669949906), SUMO Time (getSumoCurrentTime()): 69500
@(simtTime = 69.556495016436), SUMO Time (getSumoCurrentTime()): 69500
@(simtTime = 69.57661564607), SUMO Time (getSumoCurrentTime()): 69500
@(simtTime = 69.585050821124), SUMO Time (getSumoCurrentTime()): 69500
@(simtTime = 69.597744739841), SUMO Time (getSumoCurrentTime()): 69500
@(simtTime = 69.619885147893), SUMO Time (getSumoCurrentTime()): 69500
@(simtTime = 69.622955216264), SUMO Time (getSumoCurrentTime()): 69500
@(simtTime = 69.891755541142), SUMO Time (getSumoCurrentTime()): 69500
@(simtTime = 69.895170683386), SUMO Time (getSumoCurrentTime()): 69500
@(simtTime = 70.0001), SUMO Time (getSumoCurrentTime()): 70000
```
Note: Oment++ time is in (s) but sumo is in (ms).

I fixed the .cproject file, I guess the old change was due to compiling my veins in different platform.  Also, I styled my code using clang-format (`.clang-format`). 


Best. 
Hamzah

**Comment by abdelaha** [comment]
Hello Sommer,

I don't use getSumoCurrentTime() in my project anymore and I did remove it from the pull request. Now, I just added getRoadMapPos(). 


Best,
Hamzah

**Comment by sommer** [comment]
Much appreciated, thanks! I've also added a smoke test, then merged your code.

**Pull request merged**
