### PR TITLE
add VeinsInetManagerForker

### PR DESCRIPTION
**Pull request by michele-segata**
This commit adds the forker manager for Veins INET

### CODE REVIEW

**Comment by sommer** [comment]
I like the idea in principle, but it seems to duplicate some code and it seems to be available only for the `veins_inet3` subproject. The individual added complexity is certainly not very high, but with new `TraCIScenarioManager*` classes on the horizon it multiplies quickly. Any idea how this can be made more general?

**Comment by michele-segata** [comment]
I agree with the code duplication issue. Ideally, it should simply inherit from TraCIScenarioManagerForker AND VeinsInetManager at the same time. I've tried the lazy naive way to simply inherit from both classes, but it doesn't work. The compiler throws an ambiguity error.
So I guess the option here is to have a base class defining the `preInitializeModule` and the `updateModulePosition` (call it `VeinsInetManager`) and then define two classes (`VeinsInetManagerLaunchd` and `VeinsInetManagerForker`) which both inherit from the base `VeinsInetManager` and from `TraCIScenarioManagerLaunchd` and `TraCIScenarioManagerForker`, respectively.
The only issue I see with this is that, name-wise, it would not be backward compatible, as the `VeinsInetManager` class would be renamed to `VeinsInetManagerLaunchd`, but this was probably a mistake since the beginning, as the current definition is
```cpp
class VEINS_INET_API VeinsInetManager : public TraCIScenarioManagerLaunchd {
```
If you like the idea I can give it a try, and if this works fine for `veins_inet3` I can do something similar for `veins_inet`.

**Comment by sommer** [comment]
In theory, that would be the best idea. If we don't want to break the API, though, we might have to go with `VeinsInetManagerBase` or something similar as the name of the base class instead (so inheritance would be `~erBase -> ~er` (which would use launchd [*]) and `~erBase -> ~erForker`.

I know this is less-than-ideal and I would be happy to mark `~er` deprecated in favour of a new `~erLaunchd` with identical functionality, but I see no sensible other way beyond this obvious mistake on my part.

**Comment by michele-segata** [comment]
What about something like 00c20ba? Both the launchd and the forker work on my tests.

**Comment by sommer** [comment]
Merged - much appreciated!

**Comment by michele-segata** [comment]
My pleasure

**Pull request merged**
