### PR TITLE
Adding workflow

### PR DESCRIPTION
**Pull request by behrisch**
This adds a github actions workflow building omnet and veins and running with three versions of sumo:

- the plain ubuntu sumo (currently 1.4.0)
- the ppa version (latest release, currently 1.9.1 and broken for veins)
- the nightly build from the Python package index

The workflow runs on all pushes and PRs to the veins repo and every night to check changes in SUMO. 

Possible optimizations include:

- in the scheduled nightly run only test the nightly sumo
- cache the omnet build results

### CODE REVIEW

**Comment by sommer** [comment]
Great idea! Trying my best to get this integrated, but it seems most of the functionality only works if all of the Github specific directories and files are on the default (at the moment: `master`) branch. Maybe I'll need to move this to a different repo before it starts working.

**Comment by behrisch** [comment]
What I can see here https://github.com/sommer/veins/actions/runs/845374392  looks to me like it is working already. All three builds start and the ppa one fails as expected because sumo 1.9.1 does not work with the current veins.

**Comment by behrisch** [comment]
> Great idea! Trying my best to get this integrated, but it seems most of the functionality only works if all of the Github specific directories and files are on the default (at the moment: `master`) branch. Maybe I'll need to move this to a different repo before it starts working.

Yes, you need to have that in master but if you want to to check PRs automatically you need it there because PRs are usually against master.

**Comment by dbuse** [comment]
For reference: I set up CI with drone for veins some while ago. Maybe some of that is useful here as well.

See: https://github.com/dbuse/veins/tree/ci/drone and https://github.com/dbuse/veins/blob/ci/drone/.drone.yml

**Pull request merged**
