### PR TITLE
Add TraCI methods to TraCICommandInterface

### PR DESCRIPTION
**Pull request by johnstcn**
As part of my Master's thesis, I added some missing TraCI vehicle methods to TraCICommandInterface:
 * `getSpeed`
 * `getAngle`
 * `getAcceleration`
 * `getDistanceTravelled`
* `getLeader`

Submitting this PR in the hope that this saves someone else time in the future.
Please let me know if you need any changes or revisions!

### CODE REVIEW

**Review by dbuse — APPROVED** [review]
The code looks good to me and compiles without errors on my machine. I have not tested it with actual code that calls the new functions.

They also might be needed only rarely. As for most vehicles in Veins, values such as the speed are provided via subscriptions and then made available via the `TraCIMobility`.

However, I do see use cases for which these new functions may be helpful. Some bring in data that was previously not available (e.g., leader). Others may be available for subscribed vehicles -- but not all vehicles in Sumo may already by subscribed by Veins (due to ROIs, etc.).

**Comment by sommer** [comment]
Thanks - I appreciate it! @johnstcn, Would you mind also adding some smoke tests to [`/subprojects/veins_testsims/src/veins_testsims/traci/TraCITestApp.cc`](https://github.com/sommer/veins/blob/veins-5.0/subprojects/veins_testsims/src/veins_testsims/traci/TraCITestApp.cc)? This way, it's ensured that future updates don't break your newly added methods. Also, this would make it easier to ensure that your methods work well with all supported SUMO versions (see https://github.com/sommer/veins/blob/veins-5.0/src/veins/modules/mobility/traci/TraCICommandInterface.cc#L39)

**Comment by johnstcn** [comment]
@sommer Nice catch, I completely missed that file! I'll get cracking on those.

**Comment by johnstcn** [comment]
@sommer Sorry for the delay, does this look OK to you?

**Comment by sommer** [comment]
very much appreciated - thank you!

**Pull request merged**
