### PR TITLE
Feature subscriptions and pedestrians

### PR DESCRIPTION
**Pull request by truenicfel**
This reworks the current subscription setup and introduces a new subscribed traffic participant: **PERSON**. See the commit messages on details what this merge request contains.

### CODE REVIEW

**Comment by truenicfel** [comment]
I forgot to mention that there is an example in the *veins_inet* subproject.

**Comment by mightyCelu** [comment]
This looks really nice, thanks for the PR :)
It looks to me though as if this is quite the large addition, it might be easier to integrate, discuss, and test if the PR's commits would be submitted separately.

**Comment by truenicfel** [comment]
I see that problem and I think the best way is to not only split up the pull request but also splitting up the different commits. I can do that if its requested.

**Comment by sommer** [comment]
I'd very much appreciate seeing the individual changes as separate commits (e.g., "move stuff from file A to file B"). This makes it much easier to follow the changes.

It would also be a great help if you could already format the code according to the conventions followed by other code in Veins.

- Most importantly, never insert a (hard) line break just because a line reached a certain length. This makes diffs unwieldy - and if something changes in that statement later, many unrelated lines will need to be changed because of re-wrapping. Rather, split such code into two statements. That said, if you feel like a (hard) line break makes code easier to read (e.g., formatting a matrix as a matrix; or: splitting long lists into one line per item), do feel free to add one.
- Use `#pragma once` instead of `#ifdef`/`#define` include guards.
- Break `#include` statements into blocks separated by newlines:
  1. first, includes from the standard library
  2. then, the `veins/veins.h` include file (for `.h` files) or the corresponding `.h` file (for `.cc` files)
  3. then, all the rest
- The rest can be automatically formatted (using `make formatting-strict`), so it's not that important (but do feel free to apply it, so the patch is closer to what will end up in Veins)

**Comment by truenicfel** [comment]
> Most importantly, never insert a (hard) line break just because a line reached a certain length. This makes diffs unwieldy - and if something changes in that statement later, many unrelated lines will need to be changed because of re-wrapping. Rather, split such code into two statements. That said, if you feel like a (hard) line break makes code easier to read (e.g., formatting a matrix as a matrix; or: splitting long lists into one line per item), do feel free to add one.

Is this relevant for comments? I assume no.

**Comment by truenicfel** [comment]
So here is what I did/will do:
The merge request will be split up into 2 different merge requests:

1. Rework of subscriptions and person subscriptions. Basically everything in directory *subscriptionManagement*.
2. Changes to existing project files and example for pedestrians.

I did my best to fix the formatting (line breaks, includes and pragma once) and split everything up into smaller commits. After the first merge request is accepted I will open the second one. 

---> https://github.com/sommer/veins/pull/148

**Pull request closed without merging**
