### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by jheinovski**
This PR updates the project's documentation.

* Use markdown documentation from repository for doxygen and github
* Use intro text from website for documentation
* Improve doxygen generation (html, latex)

### CODE REVIEW

**Comment by jheinovski** [comment]
Please note: as a new version of Veins is / will be released, the version number in the `doxy.cfg` has to be updated before merging.

**Comment by jheinovski** [comment]
Thanks for the suggestion @mightyCelu! I pushed a version which automatically fills the version number in 7b9343f.

**Comment by jheinovski** [comment]
I updated my pull request because I made some minor changes. Overall however, the suggested changes are still the same.

At a later point in time, we might want to get rid of the extra readme from Mixim and add a reference to it to the main readme file.

**Comment by sommer** [comment]
This changes a lot of things at once. May I please ask to discuss this in separate pull requests?

**Comment by jheinovski** [comment]
I created individual PRs for all the changes made in this request:

#128 #129 #130 #131 #132

**Pull request closed without merging**
